/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

function sumOfEvenFibsBelowN(n) {
  let fibs = [0, 1];
  let count = 3;
  let runningSum = 0;
  while (count <= n) {
    const nextFib = fibs.reduce((a, b) => a + b);
    if (nextFib % 2 === 0) {
      runningSum = BigInt(runningSum) + BigInt(nextFib);
    }
    fibs[0] = fibs[1];
    fibs[1] = nextFib;
    count++;
  }

  return runningSum;
}

console.log(sumOfEvenFibsBelowN(4000000));
